image: nextcloud

stages:
  - test

sync_api_test:
  variables:
    MYSQL_DATABASE: "nextcloud"
    MYSQL_USER: "ci"
    MYSQL_PASSWORD: "ci-password"
    MYSQL_HOST: "mysql.local"
    NEXTCLOUD_ADMIN_USER: "ci-admin"
    NEXTCLOUD_ADMIN_PASSWORD: "ci-admin-password"
  services:
    - name: mariadb:10.5
      command: ["--transaction-isolation=READ-COMMITTED --binlog-format=ROW"]
      alias: mysql.local

  script:
    - curl -I http://localhost:8080
