image: docker/compose:latest

before_script:
  - apk add node
  - apk add npm
  - npm ci

services:
  - docker:dind

stages:
  - test

sync_api_test:
  script:
    - cd test
    - echo "$ENV" > .env
    - echo "$CYPRESS_ENV_JSON" > cypress.env.json
    - docker-compose up -d
    - sleep 180
    - docker exec -it $(docker ps -qf "name=app") sh -c 'chown www-data:root custom_apps'
    - npm test
  after_script:
    - docker-compose down -v
