image: docker/compose:latest

before_script:
  - apk add nodejs npm xvfb
  - cd tests && npm ci
  - echo "$ENV" > .env
  - echo "$CYPRESS_ENV_JSON" > cypress.env.json

services:
  - docker:dind

stages:
  - test

app_tests:
  script:
    - docker-compose up -d
    - sleep 180
    - docker exec $(docker ps -qf "name=app") sh -c 'chown www-data:root custom_apps'
    - npm test
  after_script:
    - cd tests
    - docker-compose down -v
