image: docker/compose:latest

before_script:
  - apk add nodejs npm xvfb
  - cd tests
  - echo "$ENV" > .env
  - echo "$CYPRESS_ENV_JSON" > cypress.env.json

services:
  - docker:dind

stages:
  - test

app_tests:
  script:
    # Start containers
    - docker-compose up -d
    # Fix permissions of custom apps folder
    - docker exec $(docker ps -qf "name=app") sh -c 'chown www-data:root custom_apps'
    # Get CID of this container
    - export CID=$(basename $(cat /proc/1/cpuset))
    # Get the IP of this container
    - export SERVER_IP=$(getent hosts $(hostname) | awk '{ print $1 }')
    # Run tests in cypress container
    - docker run -i -v "$(pwd)"/tests:$CI_BUILDS_DIR/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME -w $CI_BUILDS_DIR/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME cypress/browsers:node14.17.0-chrome88-ff89 sh 'npm ci && npx wait-on http://$SERVER_IP:8000 && npm test'
  after_script:
    - cd tests
    - docker-compose down -v
