image: nextcloud

stages:
  - test

sync_api_test:
  variables:
    MYSQL_DATABASE: "nextcloud"
    MYSQL_USER: "nextcloud"
    MYSQL_PASSWORD: "ci-password"
    MYSQL_HOST: "mysql.local"
    NEXTCLOUD_ADMIN_USER: "ci-admin"
    NEXTCLOUD_ADMIN_PASSWORD: "ci-admin-password"
    MARIADB_ROOT_PASSWORD: "ci-root-password"
  services:
    - name: mariadb:10.5
      command: ["--transaction-isolation=READ-COMMITTED", "--binlog-format=ROW"]
      alias: mysql.local
  script:
    - curl -I --connect-timeout 5 --max-time 30 --retry 10 --retry-delay 0 --retry-max-time 350 http://localhost:8080
